### ISSUE TITLE
How to add https url link in Azure policy non compliant message? 

### ISSUE THREAD

**Issue by dilv0055** [Azure/Enterprise-Scale#1015]
How to add clickable hyperlink/ url link in Azure policy non compliant message displayed on Azure portal?

For example: 

1. We have documented for Azure tags and naming convention. 
2. And implemented Azure custom tag policy to tag minimum suggested tags as specified over the document link. 

Currently the link is displaying as simple text in non-compliance message. Is there a way to display "clickable" hyperlinks in non-compliance message?

**Comment by jtracey93** [comment]
Hey @dilv0055,

Great suggestion! However, this would be a feature request to the Azure Policy team, rather than us, via the below links:

- https://feedback.azure.com/d365community/forum/675ae472-f324-ec11-b6e6-000d3a4f0da0
- https://github.com/Azure/azure-policy/issues

I will close this issue as not something we can fix in ESLZ/ALZ, but we are also evaluating enabling non-compliance messages in ALZ by default in the coming months. So when we next speak to the policy team we will pass this on also. But please raise this yourself on the links above to get updates on it as they come 👍

Thanks

Jack
