### ISSUE TITLE
Bug Report - DMS role update fails deployment

### ISSUE THREAD

**Issue by kaevans** [Azure/Enterprise-Scale#1113]
**Describe the bug**
Using the AdventureWorks deployment, the deployment consistently fails when trying to update the DNS zone role with "RoleAssignmentUpdateNotPermitted - Tenant ID, application ID, principal ID, and scope are not allowed to be updated".

**Steps to reproduce**

1. Deploy the AdventureWorks reference implementation.
2. Observe the deployment failure. 

**Screenshots**

![image](https://user-images.githubusercontent.com/7107098/201226848-6788d350-c402-4628-9d13-7e2347f4c4a8.png)

**Comment by jtracey93** [comment]
Hey @kaevans,

This is most likely due to the fact that the environment you are deploying to has not had previous role assignments cleaned up. If you check the Connectivity Subscription and remove any role assignments that are there, likely with "identity not found" and then redeploy this should fix it for you.

Thanks

Jack

**Comment by jtracey93** [comment]
Closing as stale
