### ISSUE TITLE
Feature Request VM Monitoring Policy

### ISSUE THREAD

**Issue by guidovbrakel** [Azure/Enterprise-Scale#1174]
I would like to use this policies to deploy vm monitoring to an exiting enviroment, but we have two la (multi homing) https://github.com/Azure/Enterprise-Scale/blob/1816c81e22ef5d17277ba800d8eca24cc307de95/eslzArm/managementGroupTemplates/policyAssignments/DINE-VMMonitoringPolicyAssignment.json

**Comment by guidovbrakel** [comment]
How can we add two la's to this policy: https://github.com/Azure/Enterprise-Scale/blob/1816c81e22ef5d17277ba800d8eca24cc307de95/eslzArm/managementGroupTemplates/policyAssignments/DINE-VMMonitoringPolicyAssignment.json

**Comment by jtracey93** [comment]
Hi @guidovbrakel,

Thanks for raising the issue/feature request. This is a built-in policy (https://www.azadvertizer.net/azpolicyinitiativesadvertizer/55f3eceb-5573-4f18-9695-226972c6d74a.html) and one we do not maintain in ALZ.

Therefore please review the ["Getting Support" section](https://github.com/Azure/azure-policy#getting-support) of the azure-policy repo for details on how to log requests like this to the Product Group.

On a side note, I would carefully review whether enabling a single VM reporting to 2 workspaces for VM Insights is supported via the MMA agent enablement, which this policy is using. And even if so be aware of potential risk of increased costs due to data duplication etc.
