### ISSUE TITLE
Bug Report: Deny-Private-DNS-Zones.json 

### ISSUE THREAD

**Issue by mezzofix** [Azure/Enterprise-Scale#1185]
**Describe the bug**

The https://github.com/Azure/Enterprise-Scale/blob/main/src/resources/Microsoft.Authorization/policyDefinitions/Deny-Private-DNS-Zones.json policy definition contains 2 square brackets causing the policy deployment to fail: 

![image](https://user-images.githubusercontent.com/57439630/214320312-8ccd59cf-9737-49c5-84ae-d10804ccc60c.png)

**Steps to reproduce**

1. Navigate https://github.com/Azure/Enterprise-Scale/blob/main/src/resources/Microsoft.Authorization/policyDefinitions/Deny-Private-DNS-Zones.json
2. Deploy using using the preferred technology (Azure Portal, Terraform ….)

PS. How are the json definitions validated on your end, before being pushed to the repo ?

**Comment by jtracey93** [comment]
Hey @mezzofix, Thanks for the issue.

This is actually correct as we have documented here: https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Contribution-Guide#:~:text=When%20working%20within,normal%20%2C%5B%27

This is because of the way the ALZ portal experience works and the various loops and nested deployments we have to do some ARM escaping. 

You will need to remove one of the `[`'s when deploying manually outside of any of the ALZ implementation options

Thanks

Jack

**Comment by mezzofix** [comment]
@jtracey93 Thank you for such quick response! However, I'm a bit confused. I'm also using Terraform modules, and never had to do any ARM escaping. What am I missing ?

**Comment by jtracey93** [comment]
We handle this as part of the Terraform & Bicep modules but at the source (here) we need the escaping to support the portal deployment option
