### ISSUE TITLE
Bug Report- AZL Accelerator deploy platform DevOps and automation empty

### ISSUE THREAD

**Issue by fabriziogiovannetti** [Azure/Enterprise-Scale#1188]
**Describe the bug**
During the deployment of AZL Accelerator the part related to "platform DevOps and automation" is empty.

**Screenshots**
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/37961262/214604379-fa61ba57-01d5-4e2b-a39b-559c3cf3a0e7.png">

**Comment by jtracey93** [comment]
Hey @fabriziogiovannetti,

Thanks for reporting. This happens when you do not select a management subscription. Please select a Management Subscription and then go back to this tab and it will appear.

This is as per this condition: https://github.com/Azure/Enterprise-Scale/blob/main/eslzArm/eslz-portal.json#L840

Hope that helps

Thanks

**Comment by fabriziogiovannetti** [comment]
Hi Jack thanks for your explain. BR Fabrizio
