### ISSUE TITLE
Bug Report - Deploy-Diagnostics-WebServerFarm.json

### ISSUE THREAD

**Issue by qman-being** [Azure/Enterprise-Scale#1330]
**Describe the bug**

When trying to deploy this ARM template within Azure it results in an error

**Steps to reproduce**

1. Try to create new Policy Definition
2. Input ARM Template JSON code from repo
3. Fails to create definition

**Screenshots**

![2023-05-23_10-41](https://github.com/Azure/Enterprise-Scale/assets/84679711/3ccbb4f0-a703-4c71-9f63-c0445cd0bdf3)

Looking further into this it seems that the issue is as a result of duplicate opening square brackets within the template. If I remove these and then deploy it works fine

**Comment by jtracey93** [comment]
Hey @qman-being, thanks for the issue. This is expected behaviour as documented here: https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Contribution-Guide#:~:text=Note%3A%20When%20testing%20the%20policy%20manually%20in%20the%20portal%20or%20another%20deployment%20outside%20of%20the%20ALZ%20Accelerator%20(Portal)%2C%20you%20will%20need%20to%20remove%20the%20double%20escaping%2C%20%5B%5B%2C%20and%20revert%20to%20normal%20%2C%5B%27

Thanks
