### ISSUE TITLE
Double Square Brackets in Policy Definition for Function usage

### ISSUE THREAD

**Issue by ronarieke** [Azure/Enterprise-Scale#1352]
**Describe the bug**
The function usage in the deployment templates start with multiple square brackets:
 "name": "[[concat(parameters('sqlServerName'),'/',parameters('sqlServerDataBaseName'),'/default')]",
The same is also present in the parameter declaration:
 "location": {
                  "value": "[[field('location')]"
                },
                "sqlServerName": {
                  "value": "[[first(split(field('fullname'),'/'))]"
                },
                "sqlServerDataBaseName": {
                  "value": "[[field('name')]"
                },
                "vulnerabilityAssessmentsEmail": {
                  "value": "[[parameters('vulnerabilityAssessmentsEmail')]"
                },
                "vulnerabilityAssessmentsStorageID": {
                  "value": "[[parameters('vulnerabilityAssessmentsStorageID')]"
                }

This causes our customer to need to strip the square brackets from the policy definition.
Also, the email in the definition compares a string email address against an array email object, but that is an invalid comparison, and the compliance results fail:
Name            : Microsoft.Sql/servers/databases/vulnerabilityAssessments/recurringScans.emails
Paths           :
Type            :
DefaultPath     : properties.recurringScans.emails
DefaultPattern  :
DefaultMetadata :

 

Name            : Microsoft.Sql/servers/databases/vulnerabilityAssessments/recurringScans.emails[*]
Paths           :
Type            :
DefaultPath     : properties.recurringScans.emails[*]
DefaultPattern  :
DefaultMetadata :

**Steps to reproduce**

1.
2.

**Screenshots**

https://github.com/Azure/Enterprise-Scale/blob/main/src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Sql-vulnerabilityAssessments.json

Internal Email: Ron.Rieke@microsoft.com

**Comment by jtracey93** [comment]
Hey @ronarieke,

Thanks for the issue, however this is by design due to the way we store the definitions in a nested variable and loop/iterate over them for the portal deployment - this is documented here: https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Contribution-Guide#:~:text=Escaping%20policy%20functions,normal%20%2C%5B%27

You can find and copy the double escaped definitions either at:

- [AzAdvertizer](https://www.azadvertizer.net/azpolicyadvertizer_all.html#%7B%22col_11%22%3A%7B%22flt%22%3A%22ALZ%22%7D%7D)
- ALZ Bicep Policy Library (https://github.com/Azure/ALZ-Bicep/tree/main/infra-as-code/bicep/modules/policy/definitions/lib)

Thanks

Jack
