### ISSUE TITLE
policySetDefinitions/Deploy-Private-DNS-Zones.json

### ISSUE THREAD

**Issue by Acenl12** [Azure/Enterprise-Scale#1404]
**Describe the bug**
I'm testing with the following policy: src/resources/Microsoft.Authorization/policySetDefinitions/Deploy-Private-DNS-Zones.json

But when I check a resource in scope no private endpoint is created

**Comment by jtracey93** [comment]
Hi @Acenl12, have you reviewed and followed the guidance here: https://learn.microsoft.com/azure/cloud-adoption-framework/ready/azure-best-practices/private-link-and-dns-integration-at-scale ?

It will take around 10 minutes for the DINE policy to trigger to create the endpoint.

Also please check the policy managed identity has permissions both of the the resource but also the Private DNS Zones to perform the required actions.

**Comment by jtracey93** [comment]
Closing as no response

**Comment by jtracey93** [comment]
@Acenl12 thanks for letting us know. You may be able to make it faster by specifying the `evaluationDelay` property on the DINE policy assignment https://learn.microsoft.com/en-us/azure/governance/policy/concepts/effects#deployifnotexists-properties

**Comment by jtracey93** [comment]
You would need to set this in each child definition that is part of the initiative, but some of these are built-in which would mean you would have to clone them and create customs if you wanted to set this property.

An example of this property being set can be seen in our latest policy refresh branch we are working here: 

https://github.com/Azure/Enterprise-Scale/blob/policy-refresh-q1fy24/src/resources/Microsoft.Authorization/policyDefinitions/Deploy-SqlMi-minTLS.json#L65

Happy to re-open the issue, but could you please clarify what the issue is as we got no response from our initial reply and therefore closed 👍
