### ISSUE TITLE
MDFC VM Vulnerability Scanner Policy Issues

### ISSUE THREAD

**Issue by integyjc** [Azure/Enterprise-Scale#1439]
### Let us know the feedback or general question

Feedback - Question

It appears as part of the alzdefault polices, specifically the deploy-mdfc-config initiative, a policy is assigned to configure virtual machines vulnerability provider (Definition ID: /providers/Microsoft.Authorization/policyDefinitions/13ce0167-8ca6-4048-8e6b-f996402e3c1b)

The initiative passes a parameter for the vulnerability provider type which is set to "default", which appears to be looking for VMs to have the Qualsys scanner configured

The default value set at subscription level for this setting appears to be the mdeTVM. This causes the policy to be non-compliant within new ALZ deployments.

![image](https://github.com/Azure/ALZ-Bicep/assets/100839064/848521b5-589d-4aa2-8da1-eb7f9882e91a)

![image](https://github.com/Azure/ALZ-Bicep/assets/100839064/e1e989f2-66f6-437a-87b5-aca837c696f8)

![image](https://github.com/Azure/ALZ-Bicep/assets/100839064/9fb0f7ea-0a36-4cfd-a96d-f7966870071e)

Can someone help identity which policy is configuring the Defender for Servers vulnerability provider at the subscription level? As I feel a decision needs to be made as to whether mdeTVM or Qualsys is the desired configuration

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by integyjc** [comment]
Thanks @jtracey93 (and for changing the title!) I wasnt sure if it was a policy source issue or a BiCep assignment issue to be honest

**Comment by Springstone** [comment]
Hi @integyjc. As you identified, the built-in policy (https://www.azadvertizer.net/azpolicyadvertizer/13ce0167-8ca6-4048-8e6b-f996402e3c1b.html) we're using manages the assignment of the selected vulnerability assessment provider at the VM level. For some reason, there is a 60min evaluation delay, and this is part of the reason you're having this issue.

Subscription level vulnerability assessment is set under the environment settings of Microsoft Defender for Cloud (think you've figured that already). 
![image](https://github.com/Azure/Enterprise-Scale/assets/2101287/534521c1-73f7-4f20-9c08-1cbe7c5b101e)
We're not setting that in ALZ. There are a number of ways this can be set (a security wizard pops up from time to time asking to enable "free" security features, for example), you have enabled Microsoft Defender for Endpoint (mdeTVM is enabled by default) or someone is explicitly setting this through DfC portal; and I suspect this is now enabled by default (although I cannot test this). There is also a new preview built-in policy that will set the vulnerability assessment provider at subscription scope; however, you can only set mdeTVM as the provider (https://www.azadvertizer.net/azpolicyadvertizer/766e621d-ba95-4e43-a6f2-e945db3d7888.html).

Because of the evaluation delay above, the DfC configuration will most likely apply before the policy (mdeTvm applied before default as specified in the initiative assignment).

Options:

- Disable vulnerability assessment at subscription level (not ideal, but I have this in my environment so I can validate policy)
- Change the subscription level provider setting to match policy provider (will require manual intervention for existing resources - see this blog https://mortenknudsen.net/?p=323)
- Change policy provider to mdeTvm (by updating the assignment) which should bring everything inline

I hope this answers your query, I will be closing the issue as this isn't something we can fix directly. Feel free to re-open or create a new issue if you have additional concerns. I'll add to our backlog to investigate if it makes sense to switch from "default" (Qualys) to mdeTvm in our default assignment, as I believe this may be aligned with the long term strategy.

**Comment by Springstone** [comment]
@integyjc small update. We will be updating the default assignment to mdeTvm  as the vulnerability assessment provider as part of the next policy-refresh following guidance from PG.

**Comment by integyjc** [comment]
@Springstone great thanks for your detailed explanation and for confirming the upcoming change. We'll default to mdeTvm following this guidance
