### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by james-martin-engineer** [Azure/Enterprise-Scale#1457]
**Describe the bug**
src/resources/Microsoft.Authorization/policyDefinitions/Deny-VNET-Peer-Cross-Sub.json has too many square brackets near parameters for effect

**Steps to reproduce**

1. use code assuming its accurate

**Screenshots**

**Comment by Springstone** [comment]
Hi @james-martin-engineer, this is by design for ALZ. ALZ custom policies are not intended to be deployed as is, in order to do so you will need to replace the double brackets `[[` with a single bracket `[`. We've need to include an additional bracket to support automation tooling we use to create a single deployment when deploying the Azure Landing Zone.
You can read more here: https://github.com/Azure/Enterprise-Scale/wiki/Update-ALZ-Custom-Policies-to-Latest
