### ISSUE TITLE
Bug Report - more double square brackets

### ISSUE THREAD

**Issue by james-martin-engineer** [Azure/Enterprise-Scale#1458]
**Describe the bug**
I must be the first person on the planet to have ever used this repo. More double square brackets everywhere. Maybe people just don't use Azure for anything except me

https://github.com/Azure/Enterprise-Scale/blob/main/src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Vm-autoShutdown.json

Your parameters are garbage and need to be fixed because they do not work as is and are illegal json

lines affected
169
172
175
178
181
184
187
**Steps to reproduce**

1. Use code expecting it to work
2. failure

**Screenshots**

**Comment by Springstone** [comment]
Hi @james-martin-engineer, this is by design for ALZ. ALZ custom policies are not intended to be deployed as is, in order to do so you will need to replace the double brackets `[[` with a single bracket `[`. We've need to include an additional bracket to support automation tooling we use to create a single deployment when deploying the Azure Landing Zone.
You can read more here: https://github.com/Azure/Enterprise-Scale/wiki/Update-ALZ-Custom-Policies-to-Latest
