### ISSUE TITLE
Bug Report - moore double bracket

### ISSUE THREAD

**Issue by james-martin-engineer** [Azure/Enterprise-Scale#1461]
**Describe the bug**
At least this repo isn't run by Microsoft, for if it was, I would fire anyone associated with Azure that works in this repo
https://github.com/Azure/Enterprise-Scale/blob/main/src/resources/Microsoft.Authorization/policyDefinitions/Audit-ServerFarms-UnusedResourcesCostOptimization.json

line 53 double bracket.... but to be fair, I think EVERY SINGLE POLICY in this repo is broken. Prepare for more bug reports if thats the case

**Steps to reproduce**

1.
2.

**Screenshots**

**Comment by Springstone** [comment]
Hi @james-martin-engineer, this is by design for ALZ. ALZ custom policies are not intended to be deployed as is, in order to do so you will need to replace the double brackets `[[` with a single bracket `[`. We've need to include an additional bracket to support automation tooling we use to create a single deployment when deploying the Azure Landing Zone.
You can read more here: https://github.com/Azure/Enterprise-Scale/wiki/Update-ALZ-Custom-Policies-to-Latest
