### ISSUE TITLE
Bug Report - another double bracket... would you believe it??!?

### ISSUE THREAD

**Issue by james-martin-engineer** [Azure/Enterprise-Scale#1462]
**Describe the bug**
https://github.com/Azure/Enterprise-Scale/blob/main/src/resources/Microsoft.Authorization/policyDefinitions/Audit-AzureHybridBenefit.json
Line 84

**Steps to reproduce**

1.
2.

**Screenshots**

**Comment by Springstone** [comment]
Hi @james-martin-engineer, this is by design for ALZ. ALZ custom policies are not intended to be deployed as is, in order to do so you will need to replace the double brackets `[[` with a single bracket `[`. We've need to include an additional bracket to support automation tooling we use to create a single deployment when deploying the Azure Landing Zone.
You can read more here: https://github.com/Azure/Enterprise-Scale/wiki/Update-ALZ-Custom-Policies-to-Latest
