### ISSUE TITLE
VM Compliance: Windows machines should meet requirements of the Azure compute security baseline

### ISSUE THREAD

**Issue by jtracey93** [Azure/Enterprise-Scale#1466]
### Discussed in https://github.com/Azure/Enterprise-Scale/discussions/1465

<div type='discussions-op-text'>

<sup>Originally posted by **integyjc** November  1, 2023</sup>
Hi All, im posting this here as i'm not sure if its an issue or something we are doing wrong!

We have three separate ALZ environments (different tenants), following ALZ deployment and creation of a VM within the ALZ, all end up with the following policy as non compliant

**Initiative:** [Enforce Azure Compute Security Benchmark compliance auditing](https://portal.azure.com/#view/Microsoft_Azure_Policy/InitiativeDetail.ReactView/id/%2Fproviders%2Fmicrosoft.management%2Fmanagementgroups%2Falz%2Fproviders%2Fmicrosoft.authorization%2Fpolicysetdefinitions%2Fenforce-acsb/scopes~/%5B%22%2Fproviders%2FMicrosoft.Management%2FmanagementGroups%2Falz%22%5D/isDefinitionEdited~/false)

**Policy**:  [Windows machines should meet requirements of the Azure compute security baseline](https://portal.azure.com/#view/Microsoft_Azure_Policy/PolicyDetailBlade/definitionId/%2Fproviders%2FMicrosoft.Authorization%2FpolicyDefinitions%2F72650e9f-97bc-4b2a-ab5f-9781a9fcecbc)

It seems this policy is looking for VMs to have the AzureWindowsBaseline Guest Assignment applied to them which they do not and the policy reports non compliant. I can't see anything in ALZDefault policies which is setup to configure this guest assignment.

Is this something people are handling separately to ALZ or are we expecting VMs to get the AzureWindowsBaseline guest assignment from an ALZ or DFC policy?

Any help much appreciated!
</div>

**Comment by jtracey93** [comment]
@springstone can we take a look at this one please?

**Comment by Springstone** [comment]
Hi @integyjc, that built in policy https://www.azadvertizer.net/azpolicyadvertizer/72650e9f-97bc-4b2a-ab5f-9781a9fcecbc.html provides guidance on what is required for it to work correctly (https://aka.ms/gcpol). Basically, you need to deploy and assign "Azure Automanage Machine Configuration" (which is included in both the default "Azure best practices" configuration profiles) which requires the Automanage (formerly Guest Configuration) agent. 

We do not currently deploy and configure Automanage as part of ALZ due to the many combinations of profile configuration (for custom) and determining the scope to apply a profile to (Production/DevTest). For Azure Security Baseline, for example, you may choose to audit only, apply once and monitor, or apply and autocorrect drift. 
![image](https://github.com/Azure/Enterprise-Scale/assets/2101287/6fc8d2c9-3fc7-40db-916e-f753959cc39e)

I'll raise this with the ALZ Leads for further discussion and potential inclusion in ALZ. 

Let me know if you need any further guidance.

**Comment by Springstone** [comment]
Just a quick update, I'm digging into this a bit more, as we are deploying the guest configuration agent, but I suspect we're not assigning the Azure Security Baseline configuration. Will provide updates here.

**Comment by Springstone** [comment]
Update @integyjc. The initiative we deploy does actually work as expected (it's been about a year since I looked at this :)) but it isn't very intuitive to say the least. Let's leave Automanage out of this conversation, and let me try clarify: the "non-compliant" status actually means it's not compliant with the Azure Compute Security Baseline, and I'll paint the picture to make sure we're talking about the same issue:

You see this:
![image](https://github.com/Azure/Enterprise-Scale/assets/2101287/3e1c21ec-b689-4396-a264-4eee404f7076)
This actually means that those resources are not compliant with the Azure Compute Security Baseline.
To get the details, click on "Details" next to one of the VMs that are not compliant and you get:
![image](https://github.com/Azure/Enterprise-Scale/assets/2101287/8647b33b-b5fb-457c-b26e-3dca9275f791)

You then need to follow the "Click Here" link to get to the Azure Compute Security Baseline assessment:
![image](https://github.com/Azure/Enterprise-Scale/assets/2101287/52f0ffae-fbe2-4158-9d39-7333564ec3c2)
Which shows me the 95 non-compliant settings for my newly deployed Azure virtual machine (Windows Server 2019).

This is why it shows as non-compliant. You can of course now use the same Guest Configuration agent to remediate your machines to improve compliance, but that isn't in ALZ scope/purview. To understand more about guest configuration assignments please review : https://learn.microsoft.com/en-us/azure/governance/machine-configuration/assignments. Also look under the Quickstarts section for some ideas on how to use guest configuration to your benefit. 

I hope this makes sense and addresses your query. Please let me know either way.

**Comment by Springstone** [comment]
This policy does that https://www.azadvertizer.net/azpolicyadvertizer/72650e9f-97bc-4b2a-ab5f-9781a9fcecbc.html (which is part of the ALZ intiative https://www.azadvertizer.net/azpolicyinitiativesadvertizer/Enforce-ACSB.html) as part of the then clause (checks if it's not compliant). Is the guest configuration extension deployed on your VMs?
![image](https://github.com/Azure/Enterprise-Scale/assets/2101287/6b6e2f52-bc22-47a7-979d-e46343e2711b)

**Comment by integyjc** [comment]
Hi, yep all VM's have that extension, across the three different tenants:

![image](https://github.com/Azure/Enterprise-Scale/assets/100839064/7533139c-0901-4968-904a-5f2c515f327f)

![image](https://github.com/Azure/Enterprise-Scale/assets/100839064/2decf531-be82-4711-a2a4-cc86378fe712)


From what I can tell the policies just install the Guest extension itself but I cannot see which policy or configuration is supposed to create and assign the AzureWindowsBaseline guest assignment itself

**Comment by Springstone** [comment]
That top policy creates the guest assessment (done through the policy metadata) explained https://learn.microsoft.com/en-us/azure/governance/machine-configuration/assignments. 
Do you have any egress restrictions in place? (see https://learn.microsoft.com/en-us/azure/governance/machine-configuration/overview)

**Comment by integyjc** [comment]
@Springstone thank you I think you're onto something here. All of these environments have Azure Firewall with default routes out. They do also have outbound http and https enabled via an app rule so this should still work although I think something here is the common cause as to why the guest assignments via the mentioned policy are so unreliable

One example is where Azure firewall for some reason cannot resolve the guestconfiguration address despite being able to resolve other DNS entries!

![image](https://github.com/Azure/Enterprise-Scale/assets/100839064/76a18558-ce6c-4b89-93c2-ed941399f119)


It would be interesting to know if you've seen this before but I am viewing this now as an issue to troubleshoot and appreciate we're probably outside of an ALZ specific issue / bug

**Comment by integyjc** [comment]
@Springstone - Ok i've now got to the bottom of this. This is happening across ALZ deployments where we have azure firewall in a hub vnet with the private dns zones linked as performed as part of an ALZ deployment with hub and spoke

It seems that despite us not wanting the guest configuration service to use private link, having the privatelink.guestconfiguration.azure.com DNS zone linked to the hub, is causing Azure firewall to fail to resolve agentserviceapi.guestconfiguration.azure.com. I'm now questioning my understanding of Private link and private dns! but all behaviour i've seen for other services such as blob would cause the public endpoint to be resolved if a record did not exist in the private zone, but in this case resolution fails all together

The following error is seen on a windows client within the gc_agent log

Status Code '400'. Error Message 'Failed to issue request : uri: https://agentserviceapi.guestconfiguration.azure.com/virtualMachines/f8b99726-a6c9-47b2-bd62-22fc8e192181/metadata?api-version=2018-06-30// with error: WinHttpSendRequest: 12029: A connection with the server could not be established

The following corresponding error is shown in Azure firewall

![image](https://github.com/Azure/Enterprise-Scale/assets/100839064/7407526b-4ef4-4250-86ab-9d4452d0a78d)


If I unlink the guestconfiguration private dns zone from the hub vnet, resolution works and the guest assignment appears following a restart of the Guest Configuration Service!

**Comment by Springstone** [comment]
@intgyjc Good to hear you've found the issue and a workaround. We'll investigate the issue with our networking specialists, and let you know our findings.

**Comment by Springstone** [comment]
Hi @integyjc. The behavior is as expected, the DNS Zone for guest configuration has no entries in it, so it will reply with NXDOMAIN (as this is the authoritative DNS provider for that resource). The way to enable this for guest configuration is based on a VM tag documented here: https://learn.microsoft.com/en-us/azure/governance/machine-configuration/overview#communicate-over-private-link-in-azure
The alternative is to unlink/delete the Private DNS Zone, as you've done, if you don't require communication via Private Link. 

We'll be updating the ALZ FAQ with clearer guidance in line with this.

**Comment by integyjc** [comment]
Hi @Springstone I appreciate your efforts in helping this come to a conclusion and apologies for dragging you down this rabbit hole with us! - I can confirm that adding the recommended VM tag to a VM in our test tenant does resolve the issue with the vnet link in place for privatelink.guestconfiguration.azure.com. We will apply a policy at the ALZ level to apply this tag to VM's.

I hope this thread or some updated FAQ guidance proves useful to others as we did go round in circles a bit with this one and found overlap with Azure ARC specific documentation which didn't appear relevant to this issue, although very much was!

**Comment by msundman78** [comment]
I'm struggling with the same problem that this policy reports my newly deployed Win2022 servers as non-compliant. What is the recommended approach to deploy the Azure Compute Security Baseline on Azure VMs in regions like Sweden where Automanage is currently not available? Is there any up-to-date DSC's available to deploy? I've only found outdated 2016/2022 versions when googling myself.
