### ISSUE TITLE
Deploy-ASC-SecurityContacts is always non-compliant

### ISSUE THREAD

**Issue by NucLabs** [Azure/Enterprise-Scale#1477]
**Describe the bug**
We have this policy assigned in our ESLZ for more then a year. Since a week or two, all our (30+) subscriptions dropped to non-compliant on this policy.
I have tested and reproduced this in my own subscription, which is not part of the mentioned ESLZ

**Steps to reproduce**
1. Assign the policy definition **Deploy-ASC-SecurityContacts** to a subscription and define the _Security contacts email address_, _Effect_ and _Minimal severity (High)_ parameters
2. Wait for evaluation
3. Remediate, if necesarry
4. Wait for evaluation, the resource (subscription will be non-compliant. The reason reported is that Microsoft.Security/securityContacts/alertNotifications.minimalSeverity has no value while the Target value is "High"

**Expected behavior**
The expected behavior should be that the policy is compliant when the minimal severity setting in assignment and subscription are set to "High"

**Screenshots**
![image](https://github.com/Azure/Enterprise-Scale/assets/25298846/99bb5d46-8286-42f6-b290-f7fa26428f7b)

![image](https://github.com/Azure/Enterprise-Scale/assets/25298846/cb2b322f-0cdc-43d0-a5cd-2a6ef1cb2419)

**Comment by jtracey93** [comment]
Thanks for reporting @NucLabs.

We will investigate further.

cc: @Springstone

**Comment by Springstone** [comment]
Currently investigating, as we have seen similar for other resource providers.

**Comment by neok-g** [comment]
@Springstone I can confirm this issue for this policy. With regard to your comment with other resource providers: I have a similar issue with a built-in policy with activity log alerts: https://learn.microsoft.com/en-us/answers/questions/1421659/bug-in-built-in-activity-log-alert-should-exist-po

**Comment by Springstone** [comment]
@NucLabs and @neok-g, can I please ask that you open support tickets for your respective issues, so we can get priority from engineering, as it seems there may have been a bug introduced with a recent API update. Support tickets help get engineering priority. 
@neok-g for the Activity Logs issue, I believe a fix went in for that one a day or two ago.

**Comment by NucLabs** [comment]
Sure. Just the issue as I reported here? Or do you maybe have a more specific description that I can include in the ticket?

**Comment by NucLabs** [comment]
Support ticket 2311230050002402

**Comment by neok-g** [comment]
> @NucLabs and @neok-g, can I please ask that you open support tickets for your respective issues, so we can get priority from engineering, as it seems there may have been a bug introduced with a recent API update. @neok-g for the Activity Logs issue, I believe a fix went in for that one a day or two ago.

With regard to that fix for Activity Logs: I don't see any update on that policy yet https://www.azadvertizer.net/azpolicyadvertizer/b954148f-4c11-4c38-8221-be76711e194a.html. It is still on v1.0.0:

![image](https://github.com/Azure/Enterprise-Scale/assets/3228810/37cf71b9-bf8e-4a6f-a3cd-4831d286b0f9)

Has it not been released yet? I will create a support ticket.

**Comment by Springstone** [comment]
@neok-g this wasn't a policy issue, but rather a regression bug that was introduced in an API update. The policy isn't the problem, problem was with the resource provider and their API.

**Comment by neok-g** [comment]
@Springstone Support ticket: 2311240050000425

**Comment by torgro** [comment]
Please correct me if I am not wrong, however there are multiple issues with the policy 'Deploy-ASC-SecurityContacts'. Firstly there is an issue with the ARM API ([https://github.com/Azure/azure-rest-api-specs/issues/21260](https://github.com/Azure/azure-rest-api-specs/issues/21260)) from Oct 2022 that is still open. According to the swagger definition, a request should return a SecurityContact object with the specified properties. If you query the API, it will actually return a list of SecurityContacts objects. 

`
$subId = "1e29a493-30a3-4787-aa05-14ebb0837d65"
$url = "https://management.azure.com/subscriptions/$subId/providers/Microsoft.Security/securityContacts?api-version=2020-01-01-preview"

$tokenObj = Get-AzAccessToken

$token = $tokenObj.Token

$param = @{
    Headers = @{
        Authorization = "Bearer $token"
    }
}

Invoke-RestMethod -Method Get -Uri $url @param | ConvertTo-Json -Depth 4`

`{
    "value":  [
                  {
                      "properties":  {
                                         "alertNotifications":  {
                                                                    "state":  "On",
                                                                    "minimalSeverity":  "High"
                                                                },
                                         "notificationsByRole":  {
                                                                     "state":  "On",
                                                                     "roles":  [
                                                                                   "Owner"
                                                                               ]
                                                                 },
                                         "emails":  "security.guy@contoso.com",
                                         "phone":  ""
                                     },
                      "id":  "/subscriptions/1e8ff7d1-4c9e-4a00-8ed4-a782ff0f623f/providers/Microsoft.Security/securityContacts/default",
                      "name":  "default",
                      "type":  "Microsoft.Security/securityContacts",
                      "etag":  "\"a8a12246-d0e9-45f2-a474-27bebbf019cd\"",
                      "location":  "West Europe"
                  }
              ],
    "Count":  1
}`

The policy template also have issues with the existenceCondition which does not match the return object from the API;

` "existenceCondition": {
            "allOf": [
              {
                "field": "Microsoft.Security/securityContacts/**email**",
                "contains": "[[parameters('emailSecurityContact')]"
              },
              {
                "field": "Microsoft.Security/securityContacts/alertNotifications.minimalSeverity",
                "contains": "[[parameters('minimalSeverity')]"
              },
              {
                "field": "type",
                "equals": "Microsoft.Security/securityContacts"
              },
              {
                "field": "Microsoft.Security/securityContacts/alertNotifications",
                "equals": "On"
              },
              {
                "field": "Microsoft.Security/securityContacts/alertsToAdmins",
                "equals": "On"
              }
            ]
          },`

Aligning the template to the API:

`"existenceCondition": {
          "allOf": [
            {
              "equals": "[parameters('emailSecurityContact')]",
              "field": "Microsoft.Security/securityContacts/emails"
            },
            {
              "equals": "[parameters('minimalSeverity')]",
              "field": "Microsoft.Security/securityContacts/alertNotifications.minimalSeverity"
            },
            {
              "equals": "On",
              "field": "Microsoft.Security/securityContacts/alertNotifications.state"
            },
            {
              "equals": "On",
              "field": "Microsoft.Security/securityContacts/notificationsByRole.state"
            }
          ]
        },`

Still does not work since the API returns a list of object and not a SecurityContacts object. If some one can explain how to reference the alertNotifications.minimalSeverity in the list returned from the API, we can make policy work. Will this work:

`"field": "Microsoft.Security/securityContacts[0]/alertNotifications.minimalSeverity"`

**Comment by Springstone** [comment]
@neok-g and @NucLabs please advise if you are still experiencing issues as the original issue should be resolved.

@torgo I'm not sure I understand the issue you are facing. As a pro-tip, use "Invoke-AzRestMethod" to simplify querying Azure API via Pwsh. 
`"field": "Microsoft.Security/securityContacts[0]/alertNotifications.minimalSeverity"` will not work as `securityContacts` is not an array, it's a resource type. See https://learn.microsoft.com/en-us/azure/templates/microsoft.security/securitycontacts?pivots=deployment-language-arm-template
The policy will evaluate that the SecurityContact.emails == the list of email addresses (comma or semi-comma separated list) and evaluating it is equal to what is expected. Unfortunately, this evaluates like for like (so what is set must match exactly - same order, etc).

**Comment by NucLabs** [comment]
@Springstone Something has changed. 
I forced an evaluation on one of our subscriptions, it is still non-compliant as you can see below (time zone UTC+1). 
The info on the Compliance details is different from the one I provided in the original post: there is no link to  the 'last evaluated resource', and no **Type** header

![image](https://github.com/Azure/Enterprise-Scale/assets/25298846/7cb3989f-c2f5-4c9f-b7e4-5d6a4990a1a5)

**Comment by torgro** [comment]
@Springstone There are 2 main issues. 
1. When querying the resource/object type SecurityContacts as shown in my PowerShell example, it returns a list of SecurityContacts. It is expected to return a SecurityContacts object (see link to issue i my previous reply). 
2. The policy definition with the current existenceCondition definition, does not match the properties/object of SecurityContacts.

Regarding issue 2; The only field that matches the structure of the object SecurityContacts, is "Microsoft.Security/securityContacts/alertNotifications.minimalSeverity". All other fields must be changed to match the definition of the SecurityContacts object. In my previous post, I have changed the existenceCondition definition to match the properties of SecurityContacts (I removed the field "type" as this field has been removed in the 2020-01-01-preview version). 

Isssue 1 is still open and has been open for over a year. Question then becomes: How can we reference the single item in the list returned from the API in the existenceCondition? I cannot find any reference in the guide about this. If we cant reference a single item in a list, this policy will not work until someone fixes the API to match the swagger definition.

I suspect that the reason for "Current value" showing null/nothing/"--" (minimalSeverity screenshot) for me and for @NucLabs is because of the API returning a list of SecurityContacs (one element) and not a SecurityContacs object. My SecurityContacts object have a minimum value defined, however the policy has never been able to find/read it (always shows as null).

**Comment by NucLabs** [comment]
@Springstone  The compliance pane is back to the initial state

![image](https://github.com/Azure/Enterprise-Scale/assets/25298846/727fe9ab-99cc-455f-b241-f78711fb603d)

**Comment by neok-g** [comment]
> @neok-g and @NucLabs please advise if you are still experiencing issues as the original issue should be resolved.
> 
> @torgo I'm not sure I understand the issue you are facing. As a pro-tip, use "Invoke-AzRestMethod" to simplify querying Azure API via Pwsh. `"field": "Microsoft.Security/securityContacts[0]/alertNotifications.minimalSeverity"` will not work as `securityContacts` is not an array, it's a resource type. See https://learn.microsoft.com/en-us/azure/templates/microsoft.security/securitycontacts?pivots=deployment-language-arm-template The policy will evaluate that the SecurityContact.emails == the list of email addresses (comma or semi-comma separated string) and evaluating it is equal to what is expected. Unfortunately, this evaluates like for like (so what is set must match exactly - same order, etc).

Still experiencing the issue on my side after running remediation task.

**Comment by neok-g** [comment]
Microsoft support informed that the issue has been resolved and I can confirm that.

**Comment by NucLabs** [comment]
The issue has been solved here as well. Thanks!

**Comment by jtracey93** [comment]
closing out as resolved by PG

**Comment by neok-g** [comment]
@jtracey93 This issue seems to be back
