### ISSUE TITLE
Azure Landing Zones - Community Call - 11th March 2024

### ISSUE THREAD

**Issue by jtracey93** [Azure/Enterprise-Scale#1491]
We are excited to invite you to our 8th external Azure Landing Zones community call on Monday March 11th, 17:00 CET (16:00 UK/BST - 11:00 EST - 08:00 PST - 03:00 AEDT)

![image](https://github.com/Azure/Enterprise-Scale/assets/41163455/641f2714-c6cc-49e6-ab4a-7bb3dc20d000)

> As always this will be recorded and published to the [CAE YouTube Channel](https://aka.ms/caeyoutube) and shared via our [community calls wiki page](https://github.com/Azure/Enterprise-Scale/wiki/Community-Calls) 👍

As before we have an open agenda, so please comment below with things you would like to cover or any questions you have👍

### Registration

**Sign up for the call** [here!](https://events.teams.microsoft.com/event/b0d83a59-4709-49fe-8a11-42cfde700adb@72f988bf-86f1-41af-91ab-2d7cd011db47)

**Comment by cbezenco** [comment]
Hello Jack, it seems tha tthe sign-up for the call link above still refers to the 6th of December 2023 invitation.

Shouldnt it be updated with this link : https://aka.ms/alz/communitycallregister

**Comment by arne21a** [comment]
Hi there :)

I would be interested to hear about the decision the deprecate [rover](https://github.com/aztfmod/rover) and what this means for the [CAF terraform landing zones repo](https://github.com/Azure/caf-terraform-landingzones) by @arnaudlh.
Rover is an essential part of our processes right now and its deprecations leaves me feeling nervous about the rest of the mentioned CAF terraform project.


Other questions I have are about the general future of the [CAF terraform landing zones repo](https://github.com/Azure/caf-terraform-landingzones) by @arnaudlh and the matching  [aztfmod super module](https://github.com/aztfmod/terraform-azurerm-caf).
These repos are the core of our current caf implementation and are in my opinion an excellent approach to CAF with terraform. Still I get the impression that microsoft is trying to establish different projects with higher priorities.
So my question are:

Is there a commitment to continue maintaining these projects or even extend the amount of support for these implementations?

Is there a dedicated communication channel to discuss those projects with microsoft directly aside from gitter and GitHub issues?

If there is no long term plan to support these projects, which current implementation guidelines would you recommend to follow for a migration from these repos and for a Greenfield project in the future?

**Comment by endreigesund** [comment]
Azure monitor baseline alerts - when will policies be part of the terraform enterprise-scale module?

**Comment by jkewley** [comment]
Maybe slightly out of scope, but as an extension of what @arne21a asked above, is there a future for the vending machine modules given the promotion of AVM?
https://github.com/Azure/bicep-lz-vending

**Comment by kewalaka** [comment]
@jkewley - I am using the vending machine module alongside AVM, I missed the call this morning (didn't realise it was a 5am start for me 😊), so without the context, I personally see it migrating into a pattern module.  I don't know the bicep one as well, but from the perspective of the structure of the [existing Terraform module](https://github.com/Azure/terraform-azurerm-lz-vending/), I suspect migration would not be too hard (bit of "config block" moves perhaps).

I see this as different to the Rover/CAF platform the highly coupled nature of the config in this module would make a direct migration from this difficult.  Architectural choices within this module are what kept me away, but I do sympathise with others that have adopted it.

I see this as being one of the key things that AVM is addresses - that commitment, organised at the start, to on-going support from Microsoft, rather than the best (and very laudable) efforts of an individual within Microsoft.
