### ISSUE TITLE
Feature Request - Allow the selection of "Defender for Servers Plan 1"

### ISSUE THREAD

**Issue by mundayn** [Azure/Enterprise-Scale#1495]
Hi all,

Defender for Servers Plan 1 is 1/3 of the cost of Plan 2 ($5 v $15). 
Most of my clients find that Plan 1 is more than enough for their needs when onboarding to the Cloud after going over the differences between the two.

Please can you make it an option to allow for the selection of Plan 1 when using the portal experience, and with this you'll have to set the Vulnerability scanning to the Microsoft version, not Qualys.

The policy initative in question is: Deploy Microsoft Defender for Cloud configuration
The policy in question is: Configure Azure Defender for servers to be enabled

Thank you for your consideration!

**Comment by Springstone** [comment]
Hi @mundayn, thank you for raising this issue. 

For the first ask, defaulting to mdeTVM instead of Qualys, this is already done and will be released in the next policy refresh. 

The second ask is more challenging, as we rely on the built-in policy https://www.azadvertizer.net/azpolicyadvertizer/8e86a5b6-b9bd-49d1-8e21-4bb8a0862222.html which doesn't provide an option to specify the sub-plan (defaults to full plan). In ALZ we generally recommend full security features as a best practice, so this configuration is aligned, however, your concern is noted.

In the meantime, as a workaround, you could create a custom version of the policy adding the subPlan property:

properties: {
    pricingTier: "Standard",
    subPlan: "P1"
}

And updating the initiative to use your custom policy definition for Defender for Servers instead of the built-in. 

We will investigate with PG on how we can get this updated so we can provide configuration options when deploying ALZ.

**Comment by arrerezai** [comment]
You may now use this built-in policy instead of having to go for a workaround:
https://www.azadvertizer.net/azpolicyadvertizer/5eb6d64a-4086-4d7a-92da-ec51aed0332d.html
