### ISSUE TITLE
Feature Request - single policies should be added to policy sets

### ISSUE THREAD

**Issue by vegazbabz** [Azure/Enterprise-Scale#1610]
According to Microsoft policy documentation, all single policy definitions should be part of an initiative:

- We recommend creating and assigning initiative definitions even for a single policy definition. For example, you have policy definition policyDefA and create it under initiative definition initiativeDefC. If you create another policy definition later for policyDefB with goals similar to policyDefA, you can add it under initiativeDefC and track them together.
	- Once you've created an initiative assignment, policy definitions added to the initiative also become part of that initiative's assignments.
	- When an initiative assignment is evaluated, all policies within the initiative are also evaluated. If you need to evaluate a policy individually, it's better to not include it in an initiative.

https://learn.microsoft.com/en-us/azure/governance/policy/overview#recommendations-for-managing-policies

**Comment by Springstone** [comment]
Hi @vegazbabz, we're following up with PG, as this guidance conflicts with other guidance we've been given, and we question the reasoning of the public documentation. Will update when we get an answer.

**Comment by Springstone** [comment]
@vegazbabz turns out we're not on the incorrect path, and guidance / documentation in not accurate, and PG will be updating accordingly. This particular guidance was meant for internal teams and built-in policies/initiatives, specifically around helping customers minimize the need for assignments (due to the limits).

The guidance doesn't apply to customs, however, we do follow the best practice of grouping policies together as much as possible as long as it makes sense.

Closing this story, as we have an answer - and we're not wrong. (Expect public documentation to be updated over the next month).
