### ISSUE TITLE
Azure Defender for SQL duplicate policies

### ISSUE THREAD

**Issue by achechen** [Azure/Enterprise-Scale#1636]
**Describe the bug**
In the ALZ Policies wiki (https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Policies), you recommend assigning 
_Configure  Azure Defender to be enabled on SQL Servers and SQL Managed Instances_ policy initiative to intermediate root management group.

And then, the same document recommends assigning _Configure Azure Defender to be enabled on SQL servers_ (assignment name: _Deploy Threat Detection on SQL servers_), to the landing zones management group. This is basically a policy contained by the above mentioned policy initiative.  Is there a logic behind this that I don't understand or this is just an oversight?

**Steps to reproduce**

1.
2.

**Screenshots**

**Comment by Springstone** [comment]
Known issue, reported previously. We're working through some major updates at the moment, and Defender for Cloud team are making a bunch of changes at the moment, but will review for next refresh.

**Comment by Springstone** [comment]
To clarify the original ask, no harm no foul. At Intermediate Root, we recommend policies (that can be disabled), and at landing zones scope we also recommend policies (that can be disabled). While not intentional, we're making sure that proper security controls are in place (some may not accept at intermediate scope). 

If this is a problem for you, please re-open with detail and we'll work on addressing the concern.
