### ISSUE TITLE
Your new "Diagnostic Policies" dont support the "Dedicated" destination table

### ISSUE THREAD

**Issue by birdnathan** [Azure/Enterprise-Scale#1717]
Deprecating the old diagnostics policies is fine but the new built-in policies dont seem to support the "Dedicated" table as per #1093 

Specifically Azure Firewall and Recovery Services Vaults.

![image](https://github.com/user-attachments/assets/1ad2f03f-2de4-403e-ba01-333b6d9c008e)

To combat this with latest accelerator versions i'm currently having to use a combination of the old and new policy sets. Any guidance on this or plans to support this?

**Comment by vegazbabz** [comment]
I completely agree. It is a very bad change! 
I flagged this a while ago to the policy team, but nothing happened and no intension of changing this back then at least.

It is an incredible easy addition to the existing policy definitions that support this.
Create a parameter for "logAnalyticsDestinationType" supporting either "Dedicated" or "AzureDiagnostics" (legacy).

Microsoft even recommends to use Dedicated (resource specific) logs:
https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/resource-logs#send-to-log-analytics-workspace

And it is just a handful of resource types that actually supports it. Should be the easiest thing in the world to fix for the built-in policies:
https://learn.microsoft.com/en-us/azure/azure-monitor/reference/tables/azurediagnostics#azure-diagnostics-mode-or-resource-specific-mode

Furthermore, using the built-in policies / initiative for diagnostic settings will with guarentee drive your costs up. Lots of unneeded / unneccesary logs logged by using "allLogs".
Especially, if you are focused on security logs or similar, then you do not care about performance logs, etc. that will log a ton and drive costs up.

Due to these 2 things, I am still using custom policies for diagnostic settings, as I can control exactly which categories are logged and I can follow Microsoft best practices.
Using the current built-in policy initiative or policies will not make you follow best practice.

**Comment by Springstone** [comment]
Hi @birdnathan and @vegazbabz! Thank you for your valuable feedback. I will raise this with the PG driving diagnostic settings and let you know the outcome.
A note on allLogs vs Audit - this is dependent on the resource providers supporting logging categories, and specifically the "audit" category. Currently a subset (around 50%) or the resource providers support it. As an alternative to allLogs, you can use the audit only version of the initiative here: https://www.azadvertizer.net/azpolicyinitiativesadvertizer/f5b29bc4-feca-4cc6-a58a-772dd5e290a5.html
We have a backlog item to provide the option when deploying ALZ to choose "allLogs" or "audit" only.

**Comment by Springstone** [comment]
Hi @birdnathan and @vegazbabz! Discussed with PG and there is a multi-semester workstream to transition to using dedicated tables, they are actively working on this. Please note, all efforts are around using logging categories, which helps us standardize across resources. 
We will release as part of this next policy refresh the option to choose AllLogs or Audit (for resources that support it) categories.
If you have specific requirements, you can still use the deprecated custom policies we provide and customize for your purposes.
