### ISSUE TITLE
Alz Deployment Error: Deployment Fails when we select  Azure Firewall Tier as Basic but was successful when we select Standard

### ISSUE THREAD

**Issue by Anto4595** [Azure/Enterprise-Scale#1726]
Hello @jtracey93 @Springstone 

When I was deploying the Alz using Portal and when I select Azure Firewall tier as Standard under Network topology and connectivity the deployment was successful. To manage the cost, I was redeploying again but selected the Azure Firewall tier as Basic and the deployment got failed.

**Deployment name: alz-HubSpoke-westeurope-97ade51b-52e6-5ffa-855b-4e276d1933b3-hub**

Correlation ID: 5acd03d2-a306-450e-8e0b-b4c898a7441e

Can you check and guide what is the issue ? and how can I move further.

Thank You..

**Comment by Springstone** [comment]
@Anto4595 looks like you've stumbled on the infamous "InternalServerError", which is impossible for us to troubleshoot. We have seen this issue before, specifically when deploying Basic Azure Firewall (because it requires extra bits). The underlying issue is that two operations are trying to update the same resource at the same time. We have put a workaround in for VPN Gateway and Basic Firewall, so it would be helpful to understand the exact configuration you are deploying.

Could you share all the options selected under the networking blade, and we will try repro.

**Comment by Anto4595** [comment]
Hello @Springstone 

Thank you for the Reply.

Yes I have done  a new deployment for this.

Below is the screenshots that shows what are the options that I have selected under Networking.
![image](https://github.com/user-attachments/assets/8248b2bb-fad4-4a2b-9073-6e7c3abf83b4)
![image](https://github.com/user-attachments/assets/9e615e30-4790-4d53-912c-d1341302d3f8)

Awaiting Reply...

**Comment by Springstone** [comment]
Hi @Anto4595. As I suspected, the issue here is that the ER GW and the Basic FW are both trying to make changes to the virtual network at the same time (which is not permitted). I have validated a fix for the issue, but it will take a couple of weeks before it lands in production (extensive testing is required). 
In the meantime, you can do the deployment from this link which should work as expected:
[![Deploy To Azure](https://learn.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#view/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fspringstone%2FEnterprise-Scale%2FHSBasicFWFix%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2Fspringstone%2FEnterprise-Scale%2FHSBasicFWFix%2FeslzArm%2Feslz-portal.json)

**Comment by Springstone** [comment]
PR with fix https://github.com/Azure/Enterprise-Scale/pull/1733

**Comment by jtracey93** [comment]
Fixed in latest release https://github.com/Azure/Enterprise-Scale/releases/tag/2024-08-27
