### ISSUE TITLE
alz-SqlAuditRbac1 & alz-SqlAuditRbac2 role assignment fail

### ISSUE THREAD

**Issue by mbilalamjad** [Azure/Enterprise-Scale#1747]
**Describe the bug**
During the portal deployment, the alz-SqlAuditRbac1 & alz-SqlAuditRbac2 role assignment fail with the below error 
"Tenant ID, application ID, principal ID, and scope are not allowed to be updated. (Code: RoleAssignmentUpdateNotPermitted)"

**Screenshots**
![image](https://github.com/user-attachments/assets/8c1c88bb-5a72-4201-834c-4f3f658c894b)

**Comment by jtracey93** [comment]
Hey @mbilalamjad,

This error message appears as there is already a role assignment for the same thing at the same scope, likely due to a past deployment you have not cleared up fully.

This is documented here in the RBAC docs https://learn.microsoft.com/en-us/azure/role-based-access-control/troubleshooting?tabs=bicep#symptom---arm-template-role-assignment-returns-badrequest-status

To resolve remove any identity not found assignments at the scopes where these RBAC assignments where to be made and try again
