### ISSUE TITLE
Bug Report: Configure Microsoft Defender for Servers plan - how to remediate with subplan P1

### ISSUE THREAD

**Issue by teemukom** [Azure/Enterprise-Scale#1784]
**Describe the bug**
https://www.azadvertizer.net/azpolicyadvertizer/5eb6d64a-4086-4d7a-92da-ec51aed0332d.html

Using the policy definition above with parameters subplan "P1" and isAgentlessVmScanningEnabled "false" seems to fail when creating remediation tasks: _Extension with name 'AgentlessVmScanning' is not supported for 'VirtualMachines' plan and 'P1' SubPlan (Code: InvalidInputJson)_

**Steps to reproduce**

1. Assign Configure Microsoft Defender for Servers plan policy with subplan P1 and set isAgentlessVmScanningEnabled  to false
2. Create remediation task for that policy

**Comment by baartch** [comment]
@Springstone I totally agree with @teemukom.

Why does this fail, when `isAgentlessVmScanningEnabled` is set to `false`?
I assume, it is simply because of the fact, that `AgentlessVmScanning` is mentioned as extension. Isn't it possible to list the extension in the policy conditional to the selected plan?
