### ISSUE TITLE
Bug Report: Incorrect parameter type and default value for ambaAgServiceHook

### ISSUE THREAD

**Issue by jdrepo** [Azure/Enterprise-Scale#1792]
**Describe the bug**
There seems to be an incorrect parameter type and default value for ambaAgServiceHook.

**Steps to reproduce**

1. Deploy reference implemenation
2. Remediation of policy "Deploy AMBA Notification Assets" fails
3. Error message "'Service Uri' must not be empty. (Code: BadRequest)"

**Screenshots**

![Image](https://github.com/user-attachments/assets/485ed16a-5953-4705-bbbf-cfbc79f271f9)

Seems to me that there is an incorrect parameter 

![Image](https://github.com/user-attachments/assets/314dbd78-9408-4346-af86-956ea7a163f2)

**Fix**

![Image](https://github.com/user-attachments/assets/da1e7db4-5914-45a0-ba81-8ea3c21111eb)

Can provide pull request if needed

**Comment by arjenhuitema** [comment]
Hi @jdrepo, Thank you for your feedback; I will look into the issue. I believe that no changes are necessary to the type, as the parameter `ambaAgServiceHook `is provided as an array to the `ALZWebhookServiceUri `parameter within the AMBA template.

```
                    "ALZWebhookServiceUri": {
                        "value": "[array(parameters('ambaAgServiceHook'))]"
                    },
```

Thanks for offering to submit a PR, but please hold off for now while I investigate the cause of the issue.

**Comment by jdrepo** [comment]
Hi @arjenhuitema, thanks for the reply. May be fixing the default value is enough...

**Comment by jdrepo** [comment]
@arjenhuitema , did you find anything about this issue ?

**Comment by arjenhuitema** [comment]
Hi @jdrepo,

The problem occurs when no email address or service hook is specified on the Baseline alerts and monitoring tab. The empty string was being converted to `[""]` instead of `[]`. This caused the errors you mentioned.

A pull request has been submitted that resolves the issue by conditionally specifying the value that is to be passed to the policy assignment. 

The issue has been linked to the PR, so it will be closed upon merging the PR. 

Please feel free to reach out if you have any questions or comments.
