### ISSUE TITLE
Docs and code for the Enterprise Scale to follow the CAF naming conventions

### ISSUE THREAD

**Issue by henrikivarsson** [Azure/Enterprise-Scale#23]
Hi!

Could you please update the enterprise scale examples docs and code so that it uses the newest best practice CAF naming conventions: https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/naming-and-tagging

Thanks!

**Comment by daltondhcp** [comment]
Thank you for your feedback! 
As mentioned in the CAF article, all organizations have different requirements for things like naming and tagging. 
In this case, our fictitious companies used in our reference implementations have chosen a different naming convention. 
Since all templates are open for you to change as you wish, you can deploy the artifacts with your organizations desired naming convention.
