### ISSUE TITLE
AzOps - Error while deploying custom Policy to inherit tags from subscription

### ISSUE THREAD

**Issue by sachinthapanazure** [Azure/Enterprise-Scale#422]
**Describe the bug**
We are getting below error while creating the custom policy definition using AzOps.

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed.
"details":[{"code":"InvalidTemplate","message":"Unable to process template language expressions for resource '/providers/Microsoft.Management/managementGroups/mg-interikeapreprod/providers/Microsoft.Authorization/policyDefinitions/InheritTag-Tenant' at line '25' and column '9'. 'The deployment metadata 'SUBSCRIPTION' is not valid.'"}]}

**Steps to reproduce**

We are trying to use Enterprise Scale AzOps to deploy custom policy to "inherit tags from Subscription to Resource Groups and resources".

We have used the build-in policy "b27a0cbd-a167-4dfa-ae64-4337be671140" and changed the mode to "All" instead of "Indexed".

**Screenshots**
Below are the two JSON files used to create the custom Policy definition:

[policyDef-InheritTag-Tenant.txt](https://github.com/Azure/Enterprise-Scale/files/5916025/policyDef-InheritTag-Tenant.txt)
[policyDef-InheritTag-Tenant.parameters.txt](https://github.com/Azure/Enterprise-Scale/files/5916027/policyDef-InheritTag-Tenant.parameters.txt)

**Comment by krnese** [comment]
The issue you are facing is due to how functions and expressions are being resolved during runtime of the ARM template. As you need to use these functions in the policyDefinition, you need to "escape" this in the template itself. In short; from the policyRule object and the remaining part of the policy definition where you have "[subscription().id....]" etc, you must escape these functions using double square brackets like "[[subscription().id....]". Note that the need for double square bracket is only at the start of the expression -not at the end.

**Comment by sachinthapanazure** [comment]
Hello Kristian,

Thanks for your help !!

I am able to successfully create the custom Policy Definition after using escape for the functions as suggested.

Regards,
Sachin

**Comment by sachinthapanazure** [comment]
Closing the issue.
