### ISSUE TITLE
Trey Research

### ISSUE THREAD

**Issue by rajanbhayana** [Azure/Enterprise-Scale#446]
**Describe the solution you'd like**
Make the Domain controllers optional.
And add some policies for PAAS workloads/private endpoints so that we can leverage this for first time PAAS users too.

**Comment by krnese** [comment]
Can you help me to understand what you mean by "make the domain controllers optional"?
Regarding policies for private link, these are deployed to the top-level management group - but not assigned currently. This can be done post deployment.

**Comment by rajanbhayana** [comment]
<img width="900" alt="0" src="https://user-images.githubusercontent.com/1966429/110302128-033b7f00-804d-11eb-9fcd-12aaa7107568.png">

**Comment by krnese** [comment]
We are not planning to deploy any VMs for Domain controllers as part of the setup since this is considered to very sensitive - tier0 resources for an organization and must be treated as such. Regarding policies for private endpoint, the policy initiative will be deployed and the organization can decide where to assign this.

Hope this helps.
