### ISSUE TITLE
Template deployment failing 

### ISSUE THREAD

**Issue by akn9050** [Azure/Enterprise-Scale#597]
**Describe the bug**
Deployment is failing for https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FEnterprise-Scale%2Fmain%2Fdocs%2Freference%2Fwingtip%2FarmTemplates%2Fes-foundation.json/createUIDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FEnterprise-Scale%2Fmain%2Fdocs%2Freference%2Fwingtip%2FarmTemplates%2Fportal-es-foundation.json

I think deployment is failing after this [commit](https://github.com/Azure/Enterprise-Scale/commit/101470c6bd5da7d2f3594f3537a55b4b9134d346) in lz.json template changed (Location is removed)

**Steps to reproduce**

1. Steps are given on following URL: https://github.com/CloudLabsAI-Azure/AIW-Cloud-Adoption-Framework/blob/main/Instructions/03.md#task-1-deploy-the-management-group-structure-using-arm-template-and-policy-set-definitions

**Screenshots**
![image](https://user-images.githubusercontent.com/27498287/119964755-29771800-bfc7-11eb-9bf4-5a9932abed89.png)

Error Message: 
```
{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
        "details": [
            {
                "code": "BadRequest",
                "message": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidLocationUpdate\",\r\n    \"message\": \"The policy assignment 'Enforce-AKS-HTTPS' request is invalid. The existing assignment's location cannot be changed from 'centralus' to ''.\"\r\n  }\r\n}"
            },
            {
                "code": "BadRequest",
                "message": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidLocationUpdate\",\r\n    \"message\": \"The policy assignment 'Deny-Privileged-AKS' request is invalid. The existing assignment's location cannot be changed from 'centralus' to ''.\"\r\n  }\r\n}"
            },
            {
                "code": "BadRequest",
                "message": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidLocationUpdate\",\r\n    \"message\": \"The policy assignment 'Deny-Priv-Esc-AKS' request is invalid. The existing assignment's location cannot be changed from 'centralus' to ''.\"\r\n  }\r\n}"
            }
        ]
    }
}
```

**Comment by krnese** [comment]
It looks like you are redeploying to an existing ESLZ deployment, where we had the bug for the location on certain resources (which we fixed in the above PR), where they were not needed. To avoid this issue, you can delete the policy assignment (the ones that failed), re-run, and it should work.

Can you let me know if you can give that a try?

**Comment by liamfoneill** [comment]
Hi Kristian, I get the same error (on a totally fresh tenant). It does look like the 3 policies get assigned anyhow and from what I can tell everything is deployed. However because the deployment fails, it doesn't get to the part where it creates the Github repo and sets up CI/CD. I don't think there is a straightforward way to redeploy if it gets into this state.

Deployment correlation ID: 572740ae-9635-4cff-8caa-c961693118f2
Tracking ID: 5f58180f-7013-4ed5-ac31-309808af3d6a
serviceRequestId: fd295a8c-08c9-4e30-a10c-ea1bafd557ea
Operation ID: /providers/Microsoft.Resources/deployments/NoMarketplace-20210608091951/operations/5E6082CBEBA7ADBC

**Comment by liamfoneill** [comment]
Hi Kristian, I get the same error (on a totally fresh tenant). It does look like the 3 policies get assigned anyhow and from what I can tell everything is deployed. However because the deployment fails, it doesn't get to the part where it creates the Github repo and sets up CI/CD. I don't think there  is a straightforward way to redeploy if it gets into this state.

Deployment correlation ID: 572740ae-9635-4cff-8caa-c961693118f2
Tracking ID: 5f58180f-7013-4ed5-ac31-309808af3d6a
serviceRequestId: fd295a8c-08c9-4e30-a10c-ea1bafd557ea
Operation ID: /providers/Microsoft.Resources/deployments/NoMarketplace-20210608091951/operations/5E6082CBEBA7ADBC

**Comment by akn9050** [comment]
hi @krnese, I tried to deploy this in fresh tenant and I tried to deploy it multiple times in multiple tenants and most of the time deployments fail for these three policies. 

- Deny-Priv-Esc-AKS
- Enforce-AKS-HTTPS
- Deny-Privileged-AKS

**Comment by krnese** [comment]
We have identified the following:
If you have previously deployed ESLZ to your tenant before we fixed this bug, and then later deleted the management groups that got created, and now rerunning using the same ESLZ prefix (recreate the management groups), you can get this error.

Can you pls ensure you deploy and create a new unique ESLZ Company Prefix name, that you have not used before, and let me know how it goes?

**Comment by akn9050** [comment]
Hi @krnese, thanks for prompt response, we will check on this and let you know.

**Comment by krnese** [comment]
Any updates on this?

**Comment by jtracey93** [comment]
Closing issue as no response in 21 days. Please re-open if still an issue 👍 

Thanks
