### ISSUE TITLE
Private DNS policy set (initiative) is not visible after deploying policies.json template

### ISSUE THREAD

**Issue by sssangle** [Azure/Enterprise-Scale#709]
Hi Team, I deployed policies.json ARM template as suggested by @jtracey93  using below commands

New-AzManagementGroup -GroupId 'testing'

New-AzManagementGroupDeployment -ManagementGroupId testing -Location northeurope -Name eslzPolicies -TemplateUri "https://raw.githubusercontent.com/Azure/Enterprise-Scale/main/docs/reference/adventureworks/armTemplates/auxiliary/policies.json" -topLevelManagementGroupPrefix testing

but I did not find private DNS policy initiative ( Configure Azure PaaS services to use private DNS zones ) under custom policies  on management group scope can you please check this.

When I am deploying from enterprise scale UI template I can see this policy set

![image](https://user-images.githubusercontent.com/86301556/126966570-ce1f0f3d-7fb2-48b7-89f8-161a6c4bf3a5.png)

**Comment by jtracey93** [comment]
Hi @sssangle,

Thanks for raising this. As per the [What's New? page](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new#july-2021) we have made some significant changes to the portal experience and have restructured all of the ARM templates that live behind this.

The above commands still use the old templates, which we plan to clean-up and remove soon, which is why the policy initiative (set) isn't deployed when using the PowerShell commands.

The new policy definition files can be found here: https://github.com/Azure/Enterprise-Scale/tree/main/eslzArm/managementGroupTemplates/policyDefinitions

So if you adjust the above PowerShell to deploy these instead you will get the "Configure Azure PaaS services to use private DNS zones" initiative 👍

We are also going to be realisng a document that explains how to deploy the ARM template in a "DIY" fashion using PowerShell in the coming weeks, so lookout for that on the [What's New? page](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new#july-2021)

Thanks

Jack

**Comment by sssangle** [comment]
Thanks @jtracey93 for quick response . I will try new template and test it
