### ISSUE TITLE
How to deploy to Management Group that not the Root MG

### ISSUE THREAD

**Issue by Ashley72** [Azure/Enterprise-Scale#748]
**Describe the solution you'd like**
It would be useful to have instructions on how to deploy to a different management group other than root. This will help to be able to deploy canary environment for testing and developing

**Comment by krnese** [comment]
If you are referring to the reference implementation, it's by design to be created under the root management group, and create a new intermediate root so customers can migrate existing subscription into the architecture.

For generic deployments of management groups to other management groups, see the documentation and samples @ https://github.com/Azure/Enterprise-Scale/tree/main/examples/management-groups

**Comment by jtracey93** [comment]
Also review the "Canary" guidance we published here: https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/testing-approach

**Comment by Ashley72** [comment]
I was thinking that what if you have Managements groups already deployed but now want to look at migrating to ESLZ as your company matures in its use of Azure

**Comment by krnese** [comment]
> I was thinking that what if you have Managements groups already deployed but now want to look at migrating to ESLZ as your company matures in its use of Azure

You can find the 'do-it-yourself' guidance here: https://github.com/Azure/Enterprise-Scale/tree/main/eslzArm#do-it-yourself-deployment-instructions-for-enterprise-scale-using-azure-powershell

**Comment by jtracey93** [comment]
You can deploy the Management Group structure alongside any existing hierarchy in your tenant today with what we provide.

You can then migrate, following the brownfield guidance we have here: https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/transition 

_**p.s. The brownfield guidance is being updated before the end of the year with more scenarios and guidance 👍**_
