### ISSUE TITLE
Geo Redundant Services Can't use Single Private DNS Zone

### ISSUE THREAD

**Issue by scottstout** [Azure/Enterprise-Scale#871]
The guidance indicates that you should use a single Private DNS Zone globally for a given PAAS service (e.g. storage accounts). However, if you plan to deploy geo-redundant applications w/ geo redundant storage, you will need a private endpoint for both your primary and secondary region. Each of these private endpoints will have a different IP. You can't (to my knowledge) put two private DNS Zone A records for the same storage account. To make this work for Geo Redundant scenario, you need a Private DNS Zone per region per service.

**Comment by krnese** [comment]
Thanks Scott, can you point me to where this is mentioned in the guidance?

**Comment by jtracey93** [comment]
Hey @scottstout,

Have you seen the below taken from: https://docs.microsoft.com/en-us/azure/storage/common/storage-private-endpoints#creating-a-private-endpoint

"For read access to the secondary region with a storage account configured for geo-redundant storage, you need separate private endpoints for both the primary and secondary instances of the service. You don't need to create a private endpoint for the secondary instance for failover. The private endpoint will automatically connect to the new primary instance after failover. For more information about storage redundancy options, see Azure Storage redundancy."

You can use the same DNS zone as it is a global resource, you just deploy it into a resource group in a region for metadata storage. 

Also this is different per PaaS service so therefore you should review each of their respective guidance for failover scenarios when using private link. For example Azure SQL can use Failover Groups, which are different to how Storage Accounts failover.

Hope that helps

Let us know👍

**Comment by scottstout** [comment]
@jtracey93 Doesn't this assume you are still wanting to access the failed-over storage account from the original region? If the region is down we want to access the storage account from the DR region (a different VNET). 

@krnese here is an example (but I think the policies also assume a single private dns zone globally):

"Please note that while the previous diagram depicts a single hub and spoke architecture, this guidance is applicable to scenarios where there are multiple hub and spoke networks across multiple Azure regions. In this case, the hub VNets in all regions should be linked to the same Azure Private DNS zones."
https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/private-link-and-dns-integration-at-scale#private-link-and-dns-integration-in-hub-and-spoke-network-architectures

**Comment by jtracey93** [comment]
Hey Scott,

Just a holding message to say we are investigating this a bit further internally and will come back to you 👍

For storage (and some others) it very much depends on the failure you are trying to protect from. E.g. and entire region outage or just a service outage in a region or both.

If you can share any details around what scenario you are trying to protect here that would be appreciated.

**Comment by scottstout** [comment]
@jtracey93 in this case we are trying to protect against regional outage and have a full DR region.

**Comment by jtracey93** [comment]
Hi @scottstout,

Thanks for coming back to me on the scenario here 👍

At this time there are 2 options, which are more product/service related rather than ESLZ (but it's guidance we are happy to provide our opinion on).

**Option 1 - Preferred**

- Keep using centralised private DNS zones as per our guidance: https://docs.microsoft.com/azure/cloud-adoption-framework/ready/azure-best-practices/private-link-and-dns-integration-at-scale & https://docs.microsoft.com/azure/cloud-adoption-framework/ready/azure-best-practices/dns-for-on-premises-and-azure-resources
- Enable connectivity to private endpoints required for app/service across regions with things like VNET peering etc.
- When a regional outage occurs and you invoke your DR plan
  - Manually re-create the private endpoint for the storage account in the failed over region
    -  It is very likely you'll have other manual tasks to perform as part of the DR invocation process for the app/service, especially when active/passive in it's architecture. So this is just another thing to add to the DR invocation plan.

**Option 2 - Less Preferred**

This option is less preferred due to increased complexity and management at scale that decentralised private DNS zones bring. Also the complexity when you consider on-premises DNS resolution to the private DNS zones, this can get complex to ensure the DNS request is routed to the correct region to ensure resolution and connectivity works correctly. Hence our guidance being Option 1 of centralised private DNS zones. 

- Use separate private DNS zones per region
  - Link each regions VNETs to the correct zones in the same region
- Configure individual private endpoints per region for the storage service and ensure they go to the correct private DNS zone per region
- When a regional outage occurs, there should be nothing to do from a private DNS zone/private link perspective apart from the other DR invocation steps for your app/service.

**Other points of note**

- There are differences in how each Azure service adopt private link and the associated DNS impacts, especially when considering DR scenarios.
- For example Azure SQL uses Failover Groups which follows an active/active pattern and therefore there is nothing to do in the event of a regional outage from a private DNS zone/private link perspective when using centralised DNS zones.
- Therefore, each Azure PaaS service that you use in your application/needs some consideration of how this behaves in DR scenarios that are relevant to you
- Re-creating private endpoints manually in the event of a regional outage can be very easily scripted/automated in various fashions to make this part as fast/smooth as possible so the perceived "burden" is a lot less than perhaps first thought.

**Finally**

Thanks for raising this issue, firstly. As you can see this is more of a per service and private link related issue, rather than ESLZ specifically. However, we can certainly help provide guidance here.

With that in mind i have added to our internal backlog to update the guidance here: https://docs.microsoft.com/azure/cloud-adoption-framework/ready/azure-best-practices/private-link-and-dns-integration-at-scale in the new year with some of the team with the considerations and guidance I have shared above.

I hope this helps and I will now close this issue as there is nothing further to do, please keep an eye out for updated guidance early next year as above 👍👍

**Comment by scottstout** [comment]
@jtracey93  Thank you for follow up.

For the option 1 mentioned above. Is there a way to confirm that removing the private DNS Zone group for the primary region will succeed when the primary region is down?

**Comment by jtracey93** [comment]
Hi Scott, I cannot confirm however, my understanding is that the private DNS zone group is linked per private endpoint so it is unlikely you will be able to interact with it in a region outage. 

However as the dns zones are global resources you should be able to update the zone and link and new private endpoint to it 👍
