### ISSUE TITLE
Azure Landing Zone ARM template deployment failures increasing rapidly 

### ISSUE THREAD

**Issue by akn9050** [Azure/Enterprise-Scale#908]
**Describe the bug**

#### Details:

**Error Message:** 
 "code": "DeploymentFailed",
"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
Template fails with these error messages, eslz-privatedns RG not getting created, so template deployment fails:
 ```
    {
      "code": "ResourceGroupNotFound",
      "message": "Resource group 'eslz-privatedns' could not be found."
    },
    {
      "code": "ResourceGroupNotFound",
      "message": "Resource group 'eslz-privatedns' could not be found."
    },
```

![image](https://user-images.githubusercontent.com/27498287/152672848-e2a3acb3-1791-417d-a437-befda874dc9d.png)

#### Details:

Template deployment fails with the error below:
```
   {
  "status": "Failed",
  "error": {
    "code": "RoleAssignmentUpdateNotPermitted",
    "message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated."
    }
   }
```
We documented the provided resolution on earlier raised [issue  886](https://github.com/Azure/Enterprise-Scale/issues/886)
Resolution Document: https://github.com/CloudLabsAI-Azure/Know-Before-You-Go/blob/main/AIW-KBYG/AVW-Cloud-Adoption-Framework(CAF).md#3--sometimes-template-deployment-fails-with-below-error

Earlier this resolution was always working but recently it works and does not work sometime. 

![image](https://user-images.githubusercontent.com/27498287/152673036-488e1b55-c13e-446e-8206-bcecf16e40d8.png)

**Steps to reproduce**

1. Deploy the Azure Landing Zone ARM template

We at [Spektra Systems](https://spektrasystems.com/) have workshop designed Cloud Adoption Framework in 2020 and updated in 2021, we continuously add the updates to the lab as per https://github.com/Azure/Enterprise-Scale updates.
Designed Workshop guide URL: https://experience.cloudlabs.ai/#/labguidepreview/46f781e8-1925-4d74-a82b-d985e36c4da3
GitHub URL: https://github.com/CloudLabsAI-Azure/AVW-Cloud-Adoption-Framework/tree/stage/Instructions

We are delivering the Cloud Adoption Framework on scale with our [CloudLabs](https://cloudlabs.ai/) portal as part of Azure Virtual Workshop and Azure Immersion Workshops program. We provide the pre-configured tenant with required subscriptions, permissions, and pre-requisites setup. Each workshop/lab attendee gets dedicated Azure tenant with this setup, and they deploy the Azure Landing Zone ARM template as part of first exercise of the workshop. and they get teh limited time for this workshop.

Increased rate of failure in Template deployment is a terrible experience for lab attendees when after applying the resolutions provided here doesn't work after re-deploying (twice/thrice or more than that) the template with same impute parameters. It is really time consuming for lab attendees during an ongoing workshop.

Can you please revisit the template and fix these issues permanently?

Earlier Raised issues for ARM template deployment failure:
https://github.com/Azure/Enterprise-Scale/issues/886
https://github.com/Azure/Enterprise-Scale/issues/826
https://github.com/Azure/Enterprise-Scale/issues/814
https://github.com/Azure/Enterprise-Scale/issues/597

**Comment by jtracey93** [comment]
Hi @akn9050,

Thanks for raising this issue and apologies for the issues you have been seeing.

From looking back through the issues you mention above and linked to, most of these are likely due to the environments not being cleared down fully following a deployment and completion of a lab session. 

Issues that are related to an incomplete clear down of the subs and tenant are:
- Issue 2 (above)
- #886 
- #597 

When clearing down a deployment it is advised to delete/remove all of the following:

- All resources and resource groups deployed by ESLZ portal experience from all subscriptions selected
- ARM Deployments at all scopes deployed to
  - Subscription
  - Management Group
  - Tenant

Issue #826 was related to some missing docs, which we resolved ASAP once you raised the issue. But this is not related to ARM.

Issue #814 is something we are working on with the relevant engineering teams to improve this, but this is due to a RACE condition. I have added this as evidence to our master issue for this in #902 

**Summary**

A full clear down of your tenants, subscriptions etc. as described above after each lab run is strongly suggested here as this is where most of the issue mentioned above stem from. 

To assist with clear downs I did actually create a script to assist here for my own lab environments and testing that may be of use to you here: https://github.com/jtracey93/PublicScripts/tree/master/Azure/PowerShell/Enterprise-scale 

> ⚠️🔔🚨 This script removes all resources, deployments etc. within/beneath a specified management group hierarchy.
> **USE WITH EXTREME CAUTION AND ONLY ONCE YOU HAVE READ THE `README.md` IN THE FOLDER FIRST AND UNDERSTAND IT'S POTENTIAL IMPACTS AND RISKS!**

As for #814 please keep an eye on #902 as we progress with the engineering teams on this internally. We also have a documented workaround for this as shown in #902 

I will close this issue now as we are tracking raised elsewhere as detailed above. I hope the detailed explanation helps and if you have any issues please continue raising issues here on the repo for support 👍👍👍
