### ISSUE TITLE
Bug Report - Documentation - Wiki home page links seems broken 

### ISSUE THREAD

**Issue by cbezenco** [Azure/Enterprise-Scale#925]
**Describe the bug**
Accessing the links under https://github.com/Azure/Enterprise-Scale/blob/main/docs/wiki/Home.md page return 404.

**Steps to reproduce**

1. Go to https://github.com/Azure/Enterprise-Scale/blob/main/docs/wiki/Home.md
2. Click any links on the home page

**Screenshots**
![Screenshot 2022-02-25 142725 - ESLZ wiki page](https://user-images.githubusercontent.com/12773102/155723124-e13f829e-10bf-4761-a2ea-1caafefe70dc.png)

**Comment by jtracey93** [comment]
Hey @cbezenco,

Thanks for raising this issue. 

This is occurring as you are accessing the docs via the repo instead of via the Wiki.

If you use this link and access the wiki via the wiki tab, these all work 👍https://github.com/Azure/Enterprise-Scale/wiki

![image](https://user-images.githubusercontent.com/41163455/155725432-f585aa3b-7099-426a-86ed-45c64c4ad714.png)

However, I will raise a PR to fix this so they work from both places, just in case.

**Comment by zebak007** [comment]
Thanks for the workaround :-)

**Comment by cbezenco** [comment]
Thanks for the workaround :-)
