### ISSUE TITLE
Why do ESLZ utilize copies of built-in policies?

### ISSUE THREAD

**Issue by vegazbabz** [Azure/Enterprise-Scale#981]
If you look at the list of "custom" policies here: 
https://github.com/Azure/Enterprise-Scale/blob/main/docs/ESLZ-Policies.md
then you will see, e.g., the policy "Deploy Diagnostics settings for Key Vault to Log Analytics workspace". Version is 1.0.0.

However, if you look here for the built-in policies https://docs.microsoft.com/en-us/azure/governance/policy/samples/built-in-policies#monitoring you will find "Deploy Diagnostic Settings for Key Vault to Log Analytics workspace". Version 2.0.0.
A complete duplicate of the first one. Only difference is some updated logic and a DefaultValue being true instead of false.
However, this can be dealt with using parameters when deploying - I assume you never just deploy in the blind?

So why are the majority of ESLZ policies made as custom policies, when they are basically built upon the built-in policies?
This means the client will not get any version upgrades from Microsoft, but has to update policies themselves if they are actually noted as updated in [github.com/Azure/Enterprise-Scale/wiki/Whats-new](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new)

**Comment by jtracey93** [comment]
Hey @vegazbabz,

Thanks for raising this. 

We are currently in the process of reviewing all the ALZ policies and whether they have been replaced by built-in's.

Some of them may seem like clones, but this is only done when the policy that is built-in cannot be used as it is due to a missing effect type or option as a parameter inputs that we can change on assignment, as you say.

I will mark this one down and we will review. 

Please note our goal is to not maintain custom policies but to utilize built-in policies wherever possible 👍
